on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install sphinx
      run: pip install sphinx sphinx-rtd-theme sphinx-tabs
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Bootstrap
      run: go install ./cmd/dawn
    - name: Build
      run: dawn
    - name: Test
      run: go test ./... -coverprofile=coverage.out
    - name: Upload coverage data
      if: ${{ matrix.os != 'windows-latest' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out
        fail_ci_if_error: true
        verbose: true
        env_vars: OS
        token: ${{ secrets.CODECOV_TOKEN }}
