on:
  push:
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install tools
      uses: jdx/mise-action@v2
      with:
        experimental: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Bootstrap
      run: go build -o ./bin/dawn ./cmd/dawn
    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: .dawn/build
        key: dawn-build-${{ github.ref }}
    - name: Build
      run: ./bin/dawn
    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: .dawn/build
        key: dawn-build-${{ github.ref }}
    - name: Test
      run: gotestsum -- ./... -coverprofile=coverage.out -timeout 1m
    - name: Upload coverage data
      if: ${{ matrix.os != 'windows-latest' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out
        fail_ci_if_error: true
        verbose: true
        env_vars: OS
        token: ${{ secrets.CODECOV_TOKEN }}
