on:
  push:
    tags: ['v*.*.*']
name: goreleaser
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install sphinx
      run: pip install sphinx sphinx-rtd-theme
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
