on:
  push:
    tags: ['v*.*.*']
name: goreleaser
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install tools
      uses: jdx/mise-action@v2
      with:
        experimental: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
