on:
  push:
    tags: ['v*.*.*']
name: goreleaser
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install sphinx
      run: pip install sphinx sphinx-rtd-theme
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
